### ISSUE TITLE
Mention me please

### ISSUE THREAD

**Issue by Almo7aya** [YemenOpenSource/impactful-contributions#1]
https://github.com/ritwickdey/vscode-live-server/pull/330
https://github.com/preactjs/preact/pull/1484
https://github.com/nvim-tree/nvim-tree.lua/pull/1637
https://github.com/LunarVim/LunarVim/pull/3180
https://github.com/pystardust/ani-cli/pull/31

**Comment by WatheqAlshowaiter** [comment]
@Almo7aya 

done.
